$.ajax({
    type:"get",
    url:"http://agaram.academy/api/action.php",
    data:{},
    success:function(h){
        console.log("h",h)
    },
    error:function(e){
        console.log("e",e)
    }
})
console.log('d')